### ISSUE TITLE
✋ [MEMBER] - <cgl>

### ISSUE THREAD

**Issue by cgl** [django-commons/membership#100]
### Why do you want to join?

I think this is a great initiative and I believe I can contribute in several ways both as a contributor and by sharing my experience in various ways that would benefit the team and the initiative overall.

### Which project(s) are you looking to contribute to?

I don't have any specific project(s) in mind yet.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Invited! Thank you for joining and for your efforts as a DSF board member!

You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? It helps the org grow :rocket:
