### ISSUE TITLE
✋ [MEMBER] - <leogregianin>

### ISSUE THREAD

**Issue by leogregianin** [django-commons/membership#104]
### Why do you want to join?

This is a great initiative and I believe I can contribute to many projects as a contributor.

### Which project(s) are you looking to contribute to?

I don't have any specific project(s) in mind yet.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by ryancheley** [comment]
Welcome @leogregianin 👋 

You should have received an invitation to join. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)?

This helps Django Commons grow.

**Comment by leogregianin** [comment]
Thank you @ryancheley
