### ISSUE TITLE
🏗️ [ADMIN] - benbacardi

### ISSUE THREAD

**Issue by benbacardi** [django-commons/membership#11]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I would like to give back more to the Django community than I currently do, and third party packages are so key to Django's popularity!
I am an individual contributor to the DSF thanks to helping out in the Discord. 

### Please tell us about your packaging experience?

As part of my day job I build and release Python packages using both setup.py and Poetry, mostly publishing to internal Nexus-hosted PyPI repositories. Far from an expert, but have *some* experience. 

### Please tell us about your GitHub Actions experience?

Extensive GitLab CI experience and some GitHub Actions experience, though mostly through using other people's actions. 

### How long do you expect to be involved with Django Commons?

As long as is needed. I don't see myself having to step away from the community for any reason any time soon, but also wouldn't want to overstay any welcome!

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks Ben! Good to see you outside of Discord too! I'm going to let this sit for a week to give time to other folks to apply.

**Comment by tim-schilling** [comment]
Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Thanks for your interest Ben! Right now the roster is full, but the expectation is that we'll cycle people in and out of roles over time. I'll circle back with you when we get to that point.
