### ISSUE TITLE
✋ [MEMBER] - github.com/whoiskrtk2

### ISSUE THREAD

**Issue by whoiskrtk2** [django-commons/membership#114]
### Why do you want to join?

I'm an experienced back-end engineer looking to get started with open-source and give back to the Django community.

### Which project(s) are you looking to contribute to?

- django-tasks-scheduler
- django-debug-toolbar
- django-typer

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by whoiskrtk2** [comment]
Sure! [Here](https://www.linkedin.com/in/kartik285kumar/)

**Comment by cunla** [comment]
Thank you @whoiskrtk2 for joining! You'll get an invite email from GitHub. You'll have one
week to accept that. If you don't mind, after accepting, can you set your
[organization membership as public](https://github.com/orgs/django-commons/people)?
This helps Django Commons grow.

**Comment by whoiskrtk2** [comment]
I will. Thanks!
