### ISSUE TITLE
✋ [MEMBER] - jbur6789

### ISSUE THREAD

**Issue by jburns6789** [django-commons/membership#116]
### Why do you want to join?

I want to gain practical experience in the developer world. I am a new graduate and I want to continue to learn.

### Which project(s) are you looking to contribute to?

I am unsure of the available projects but I am ready to figure out where I can make an impact.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Thank you <NAME> for joining! You'll get an invite email from GitHub. You'll have one
week to accept that. If you don't mind, after accepting, can you set your
[organization membership as public](https://github.com/orgs/django-commons/people)?
This helps Django Commons grow.
