### ISSUE TITLE
✋ [MEMBER] - clintonb

### ISSUE THREAD

**Issue by clintonb** [django-commons/membership#118]
### Why do you want to join?

I am considering transferring https://github.com/jazzband/django-waffle so that I have greater administrative support. I'd rather not return it to independent status.

### Which project(s) are you looking to contribute to?

https://github.com/jazzband/django-waffle

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Thank you @clintonb for joining! You'll get an invite email from GitHub. You'll have one
week to accept that. If you don't mind, after accepting, can you set your
[organization membership as public](https://github.com/orgs/django-commons/people)?
This helps Django Commons grow.
