### ISSUE TITLE
🏗️ [ADMIN] - @carltongibson

### ISSUE THREAD

**Issue by carltongibson** [django-commons/membership#12]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

Enabling the community is the only ultimately stable approach. It’s the multiplier. 

### Please tell us about your packaging experience?

I’ve been a maintainer of packages in the Django ecosystem for a decade and more, including Django itself for a while there. 

### Please tell us about your GitHub Actions experience?

I’ve been using GHA extensively since they were introduced. 

### How long do you expect to be involved with Django Commons?

I’d expect involvement to wax and wane but, as with Django itself, more or less until the heat death of the universe. 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Oh, and hi Carlton! Thank you for posting this.

**Comment by tim-schilling** [comment]
Hi Carlton, would you be willing to be on the Code of Conduct and Security teams for the org? They'd both be managed via Google Groups.

For CoC, where upon a report occurring, we'd collect the details of the incident, discuss how to handle things, then come to an agreement on a path forward. At the conclusion of each report, we would send an email to the admin team and the CoC team with our decision (provides accountability and transparency).

For Security, upon a report, we'd collect the details of the incident, determine if it's a valid error, and facilitate coordination with the project maintainers to issue a fix.

As you can likely imagine, the involvement will be low until there's an incident.

Please let me know if this is something you'd be interested and available to do? We're looking at a 9-12 month cycle before we reassess team structures. Though you're free to step down at any point.

**Comment by carltongibson** [comment]
@tim-schilling Happy on both counts ✅

**Comment by tim-schilling** [comment]
Excellent, I think there was an issue adding you to a google group. I'll follow-up with you offline on how to resolve that. Marking this as completed.

**Comment by tim-schilling** [comment]
Hi @carltongibson, we're looking to [add new admins to the team](https://django-commons.org/blog/2026/02/03/were-recruiting-new-admins/). If you're still interested, please fill out this [Admin Interest Form](https://forms.gle/XQKb1xfL7UKPEyL18) by [March 16th, 2026 AOE](https://time.is/compare/2359_16_March_2026_Anywhere_on_earth).

We're switching to a private form submission since the community discovered public applicants tend to result in people self-selecting out. Sorry for the extra hassle!

**Comment by carltongibson** [comment]
No stress. I don't need to be admin here. There are plenty of folks currently it seems. (IIRC I misunderstood what was going on here and didn't realise the admin/member distinction at the beginning.)
