### ISSUE TITLE
✋ [MEMBER] - johnfraney

### ISSUE THREAD

**Issue by johnfraney** [django-commons/membership#128]
### Why do you want to join?

I'm looking to get back into Django development after a few years' hiatus, and contributing to open-source projects would be a great way to do that while giving back to the community. I respect the mission of Django Commons and it would be cool to be a part of it!

### Which project(s) are you looking to contribute to?

Any! I'm happy to contribute CI, type hints, unit tests, bugfixes, or maintenance tasks.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Welcome to the commons @johnfraney! Sorry for the delay, we had to review why there was an extra user in your PR 🤔 All good now though!

You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.

**Comment by johnfraney** [comment]
@tim-schilling Done and done!
