### ISSUE TITLE
🏗️ [ADMIN] - williln

### ISSUE THREAD

**Issue by williln** [django-commons/membership#13]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I would like to help the community become sustainable, and learn more about package maintenance. 

### Please tell us about your packaging experience?

I don't have a lot of packaging experience, but I am confident I could learn. 

### Please tell us about your GitHub Actions experience?

I have written GitHub actions for personal and professional use. Common use cases for me include adding linting steps to PRs, commenting on PRs, doing things on a cadence, etc. I am not afraid of GH Actions, nor am I an expert. 

### How long do you expect to be involved with Django Commons?

I would like to give it a year and see how things are going. Right now, I don't have other open-source or community commitments, though. My hope is to be involved, in a way that waxes and wanes with life, for the next several years. 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks for posting this Lacey! Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Welcome aboard as an admin Lacey! Thank you!
