### ISSUE TITLE
✋ [MEMBER] - giovannicimolin

### ISSUE THREAD

**Issue by giovannicimolin** [django-commons/membership#134]
### Why do you want to join?

I want to help maintain and contribute some changes and improvements to a few projects.

### Which project(s) are you looking to contribute to?

Django-fsm2 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks for joining @giovannicimolin! You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.

We've also added you as a team member for django-fsm2. We'll need to see if your membership is updated after you accept the org invite.

**Comment by giovannicimolin** [comment]
Thank you @tim-schilling! It's nice to be onboard. :)

I just accepted the invite and set my membership as public - looking forward to contribute a bit.
