### ISSUE TITLE
✋ [MEMBER] - jcjudkins

### ISSUE THREAD

**Issue by jcjudkins** [django-commons/membership#14]
### Why do you want to join?

I am looking for more opportunities to test and show my skills by applying them to useful projects. Further, I want to be more involved in the Django coding community. 

### Which project(s) are you looking to contribute to?

I am looking to help with any project!

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Approved

**Comment by tim-schilling** [comment]
Hi @jcjudkins, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people
