### ISSUE TITLE
🏗️ [ADMIN] - Stormheg

### ISSUE THREAD

**Issue by Stormheg** [django-commons/membership#15]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

**Introduction**

Hello, my name is Storm Heg from the Netherlands. I'm a Wagtail/Django developer and a member of the Wagtail Core team since 2021. I'm more involved with Wagtail than I am with Django and not active at all on social media, so most of you in the Django ecosystem probably won't recognise my name. Most of my contributions involve Wagtail and its ecosystem of packages as a member of [Wagtail Nest](https://github.com/wagtail-nest).

I'm also a maintainer of [django-recaptcha](https://github.com/django-recaptcha/django-recaptcha/) because I regularly use this package in my projects and thus have an interest in keeping it healthy.

**Why do I want to join**

I want to see Django Commons succeed in becoming a trusted home for packages.

Like many other software developers, I rely a lot on software written and maintained by others. I've seen software I relied on being abandoned by its maintainer, to great frustration of the users who relied on it. I appreciate there are all sorts of reasons why a maintainer might no longer have an interest in maintaining (and that's okay!). When asked to transfer maintainership, there are often rightful reservations about transferring maintainership to unknown individual(s). It's an issue of trust.

I strongly believe community maintained packages, with oversight from a trusted group of individuals, is a good response to this issue. Thank you @tim-schilling for breathing new life into this concept.

I would like to be one of the trusted individuals for Django Commons.

### Please tell us about your packaging experience?

Like mentioned before, I'm a member of Wagtail Nest and have a good amount of experience with setting up CI and PyPI release automation.

Here are some links:

- maintainer of django-recaptcha: see the [pull requests I've been involved with](https://github.com/django-recaptcha/django-recaptcha/pulls?q=involves%3Astormheg)
- maintainer of wagtail-ab-testing: see the [pull requests I've been involved with](https://github.com/wagtail-nest/wagtail-ab-testing/pulls?q=involves%3Astormheg)

### Please tell us about your GitHub Actions experience?

I've written plenty of Github Actions workflows over the years. Both for open source projects and as part of my day job.

Here are a couple of highlights:

- Set up PyPI Trusted Publishing for django-recaptcha: https://github.com/django-recaptcha/django-recaptcha/commit/791f833542fa89b05a0a4c6c70a6242c89853f15
- Migrate wagtail-ab-testing CI to Github Actions: https://github.com/wagtail-nest/wagtail-ab-testing/pull/58/files

### How long do you expect to be involved with Django Commons?

Not for eternity that's for sure.

During this initial setup phase it is vital to attract enough trusted individuals. I see plenty of applications in this repository already, good!

I'm not sure how many trusted individuals are needed for Django Commons to function properly. I fear that having to many individuals will cause a situation where important tasks are deferred to other members ('someone else will get to it').

Perhaps some sort of roster of primary admins that will rotate? I'd be happy to spend maybe half a year actively as an admin and 1,5 years on 'standby' before doing another active term. Assuming I'm still working with Django and interested in the role at that point. What's that sound like?

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Hi Storm! Thanks for posting this (and for your community contributions), I'm looking forward to meeting you!

Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by Stormheg** [comment]
Thanks Tim, looking forward to meeting you too 👍

**Comment by tim-schilling** [comment]
Welcome aboard as an admin Storm! Thank you!
