### ISSUE TITLE
🏗️ [ADMIN] - ryancheley

### ISSUE THREAD

**Issue by ryancheley** [django-commons/membership#16]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I want to be part of the group that helps to shape how support for various third party packages in Django can be maintained using a community approach. I think the community-maintained first approach is a really great idea and I want to be part of that process to learn and grow. 

Additionally,  I’d like to learn more about GitHub Actions. I have a [repo](https://github.com/ryancheley/learning-github-actions) where I was trying to learn about each of the actions, but without a project that can be challenging. This project would help to give me ‘a problem to solve’ with GitHub actions in a real world way which I am *really* excited about

### Please tell us about your packaging experience?

I have written a few packages that are available on [pypi](https://pypi.org/user/ryancheley/). They are:

- [toggl-to-sqlite](https://pypi.org/project/toggl-to-sqlite/)
- [pelican-to-sqlite](https://pypi.org/project/pelican-to-sqlite/)
- [the-well-maintained-test](https://pypi.org/project/the-well-maintained-test/)

### Please tell us about your GitHub Actions experience?

I’ve use GitHub actions to automate CI/CD processes, specifically running tests and then deploying the code for a Django project to a Digital Ocean droplet. 

Additionally I have used GA to add issues automatically to Milestones, and done a. few things with ‘GitHub Scrapping’ as Simon Willison refers to it, with an example you can see [here](https://github.com/ryancheley/ahl) with some scrapping of American Hockey League Data and [here](https://github.com/ryancheley/til) with my Today I Learned repo (which I learned from Simon Willison)

### How long do you expect to be involved with Django Commons?

I would like to be involved for 12 - 18 months. I think that provides enough time to learn and grow into a maintainer role, and document processes and gained knowledge, but not so long as to approach any burnout. 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Hi Ryan! Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Welcome aboard as an admin Ryan! Thank you!
