### ISSUE TITLE
🏗️ [ADMIN] - marksweb

### ISSUE THREAD

**Issue by marksweb** [django-commons/membership#17]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I like helping people out with the knowledge I have now, because back when I was getting started it was hard to find that know-how.

### Please tell us about your packaging experience?

I've been releasing packages for a few years. I especially like it when you get GHA to do all the hard work for you & integrate a release process using GH releases.

### Please tell us about your GitHub Actions experience?

I try to get GHA to do as much as possible to help maintain repos. I've never done anything massively complicated, but welcoming new members, running QA/test suites and then releasing to (test.)pypi are all the usual things I'll make sure are in place.

### How long do you expect to be involved with Django Commons?

I don't see an end in sight to my python/django days yet.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Hi Mark, would you be willing to be on the Security team for the org? It would be managed via a Google Group, where upon a report occurring, we'd collect the details of the incident, determine if it's a valid error, and facilitate coordination with the project maintainers to issue a fix.

There would also be monthly or quarterly summary reports via an email to the admin team to provide accountability. As you can likely imagine, the involvement will be low until there's an incident.

Please let me know if this is something you'd be interested and available to do. We're looking at a 9-12 month cycle before we reassess team structures. Though you're free to step down at any point.

**Comment by marksweb** [comment]
@tim-schilling Yeah that sounds good to me - something I'm used to already as well 👍🏼

**Comment by tim-schilling** [comment]
Perfect, thank you! The next steps will be posted to that google group in the next month or so pending people's availability.

**Comment by tim-schilling** [comment]
Hi @marksweb, we're looking to [add new admins to the team](https://django-commons.org/blog/2026/02/03/were-recruiting-new-admins/). If you're still interested, please fill out this [Admin Interest Form](https://forms.gle/XQKb1xfL7UKPEyL18) by [March 16th, 2026 AOE](https://time.is/compare/2359_16_March_2026_Anywhere_on_earth).

We're switching to a private form submission since the community discovered public applicants tend to result in people self-selecting out. Sorry for the extra hassle!
