### ISSUE TITLE
🏗️ [ADMIN] - @robhudson

### ISSUE THREAD

**Issue by robhudson** [django-commons/membership#20]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I've been looking to get more involved in Django and third-party Django app development and maintenance. I discovered Django Commons through an issue on the Django Debug Toolbar, followed the link, and liked the concept. I believe it's a fantastic initiative and would love to contribute to maintaining and supporting Django projects. Additionally, I'd like to give back to the community that stepped in to help with the Debug Toolbar when I couldn't continue due to a busy family schedule.

### Please tell us about your packaging experience?

I maintain several packages at Mozilla and am part of a PyPI team responsible for releases. Recently, I transitioned a few projects to use `pyproject.toml` and `hatchling.build`. My experience falls somewhere between beginner and expert - although I probably wouldn't self-identify as an expert on anything - I feel I have a solid understanding and practical experience in packaging and release management.

### Please tell us about your GitHub Actions experience?

I'm a big fan of GHA and we've migrated to it for most projects I'm involved in within Mozilla.

### How long do you expect to be involved with Django Commons?

I would enjoy being involved with Django Commons and I see myself contributing for the foreseeable future. While I understand that being an administrator isn't a permanent position, I would be committed to supporting the community as long as my contributions are valuable and appreciated.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks for your support, interest and time Rob! The expectation is that we'll cycle people in and out of roles over time. I'll circle back with you when we get to that point.
