### ISSUE TITLE
🏗️ [ADMIN] - laymonage

### ISSUE THREAD

**Issue by laymonage** [django-commons/membership#21]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I like the idea and I want it to be successful. I've also been looking for different ways to contribute to Django, and this seems like a great opportunity.

### Please tell us about your packaging experience?

- Set up [django-jsonfield-backport](https://github.com/laymonage/django-jsonfield-backport) from scratch, my first Django package
- Did a few [Wagtail](https://github.com/wagtail/wagtail) releases
- Set up [wagtail-modeladmin](https://github.com/wagtail-nest/wagtail-modeladmin) using Wagtail's package template, updated to use GitHub Actions and PyPI trusted publishers

### Please tell us about your GitHub Actions experience?

- django-jsonfield-backport
  - [Testing matrix with multiple databases](https://github.com/laymonage/django-jsonfield-backport/blob/master/.github/workflows/test.yml) (SQLite, PostgreSQL, MySQL, MariaDB, Oracle)
  - [Publishing via gh-action-pypi-publish](https://github.com/laymonage/django-jsonfield-backport/blob/master/.github/workflows/publish.yml)
  - Probably outdated by now
- Wagtail
  - Setting up coverage report, running tests in parallel, and general housekeeping
- wagtail-modeladmin
  - Testing with tox
  - Publishing via gh-action-pypi-publish with PyPI trusted publisher mechanism

### How long do you expect to be involved with Django Commons?

Six months, then I'll likely take a break and lurk for a while, before coming back for another six. Rinse and repeat until it's not feasible for me anymore.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks for your interest Sage! Right now the roster is full, but the expectation is that we'll cycle people in and out of roles over time. I'll circle back with you when we get to that point.

**Comment by tim-schilling** [comment]
Hi @laymonage, we're looking to [add new admins to the team](https://django-commons.org/blog/2026/02/03/were-recruiting-new-admins/). If you're still interested, please fill out this [Admin Interest Form](https://forms.gle/XQKb1xfL7UKPEyL18) by [March 16th, 2026 AOE](https://time.is/compare/2359_16_March_2026_Anywhere_on_earth).

We're switching to a private form submission since the community discovered public applicants tend to result in people self-selecting out. Sorry for the extra hassle!
