### ISSUE TITLE
✋ [MEMBER] - blaisep 

### ISSUE THREAD

**Issue by blaisep** [django-commons/membership#22]
### Why do you want to join?

I'm an aspiring Djangonaut and also seeking to improve Jazzband 
https://github.com/jazzband/help/issues/366

### Which project(s) are you looking to contribute to?

I don't have a strong preference.
My interests are trunk based development and behavior driven development.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Approved
