### ISSUE TITLE
🏗️ [ADMIN] - cunla

### ISSUE THREAD

**Issue by cunla** [django-commons/membership#23]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I have experience working with open-source packages, particularly writing github actions and I think I can contribute a lot.

### Please tell us about your packaging experience?

See [fakeredis](https://github.com/cunla/fakeredis-py), [django-tasks-scheduler](https://github.com/dsoftwareinc/django-tasks-scheduler).

### Please tell us about your GitHub Actions experience?

Certified, and well experience creating even the most complex workflows.
Also wrote a [pycharm plugin to manage GitHub Actions](https://github.com/dsoftwareinc/ghactions-manager).

### How long do you expect to be involved with Django Commons?

I have been involved in open source maintenance for about 3 years now and expect to do it forever. Naturally, it also depends on alignment with the rest of the team, etc.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks for applying Daniel! Can you fill out this form https://forms.gle/DkMxy8m19ssDosX7A and put your availability to meet on this poll? https://xoyondo.com/dp/wa1thb94i9xw1ju

**Comment by tim-schilling** [comment]
There's also some light discussion going on at https://github.com/orgs/django-commons/discussions/19

**Comment by cunla** [comment]
Hi, thx for responding. I filled both forms. I read there is a meeting tomorrow. Can you send me the invite? daniel at moransoftware.ca

I hope I can make it.

**Comment by tim-schilling** [comment]
Nope, the meeting has been cancelled. It won't be until June 17th.

**Comment by tim-schilling** [comment]
Welcome aboard as an admin Daniel! Thank you!
