### ISSUE TITLE
✋ [MEMBER] - Natim

### ISSUE THREAD

**Issue by Natim** [django-commons/membership#24]
### Why do you want to join?

I have been working with Django since 2005.
I am really enthousiastic about collaborative maintenance of Django Libraries

### Which project(s) are you looking to contribute to?

django-fsm-2

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Approved

**Comment by tim-schilling** [comment]
Hi @Natim, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people
