### ISSUE TITLE
✋ [MEMBER] - pfouque

### ISSUE THREAD

**Issue by pfouque** [django-commons/membership#26]
### Why do you want to join?

Django enthusiast since 2010, I'd like to contribute more and this initiative sounds like a great idea.
I'm already helping with the maintenance of django-mailbox

### Which project(s) are you looking to contribute to?

TLDR: `django-fsm-2`

Initially `django-fsm`, but unfortunately it was unmaintained for years, then brutally archived.
As one of my favorite libraries in my toolbelt, I started to maintain a fork for myself, then published it as `django-fsm-2`

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Approved

**Comment by tim-schilling** [comment]
Hi @pfouque, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people

**Comment by pfouque** [comment]
> Hi @pfouque, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people

Feel free!

**Comment by Stormheg** [comment]
@pfouque we (the admins) can't change membership visibility to public. GitHub leaves that choice with individuals.

To change it, find yourself in the members list and change private to public. Thanks for helping us out 👍

**Comment by pfouque** [comment]
It's done!
