### ISSUE TITLE
✋ [MEMBER] - gav-fyi

### ISSUE THREAD

**Issue by gav-fyi** [django-commons/membership#27]
### Why do you want to join?

Having worked with Django for 13+ years, and created many in-house libraries, I'm interested in contributing to OSS as and when time permits. 

### Which project(s) are you looking to contribute to?

Any. I'm not fussy :) 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Approved

**Comment by tim-schilling** [comment]
Hi @gav-fyi, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people
