### ISSUE TITLE
🏗️ [ADMIN] - ryanhiebert

### ISSUE THREAD

**Issue by ryanhiebert** [django-commons/membership#30]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I like what you’re doing and want to help

### Please tell us about your packaging experience?

tox-travis, django-safemigrate, aldjemy 

### Please tell us about your GitHub Actions experience?

I’ve used it quite a bit at several different companies, though I’m sure that this project poses unique challenges

### How long do you expect to be involved with Django Commons?

No definite timeline at this point. If I got a job that didn’t deal with Django at all, that might be a time I’d want to step back.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks for your interest Ryan! Right now the roster is full, but the expectation is that we'll cycle people in and out of roles over time. I'll circle back with you when we get to that point.
