### ISSUE TITLE
✋ [MEMBER] - g-nie

### ISSUE THREAD

**Issue by g-nie** [django-commons/membership#32]
### Why do you want to join?

I'm very interested in contributing to Django packages. I'd like to help maintain both new and older repositories.

### Which project(s) are you looking to contribute to?

[django-fsm-2](https://github.com/pfouque/django-fsm-2), since it's soon to be incorporated here, but I'm open to contributing to anything.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Hi @g-nie, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people

**Comment by g-nie** [comment]
Sure thing @tim-schilling, I hadn't even realized it was private 😶
