### ISSUE TITLE
🛬 [INBOUND] - django-debug-toolbar

### ISSUE THREAD

**Issue by tim-schilling** [django-commons/membership#34]
### What's the URL to the project?

https://github.com/jazzband/django-debug-toolbar

### Who are the current maintainers?

@matthiask, @tim-schilling

### Does the project have the required attributes?

- [X] Does the project have tests?
- [X] Does the project have documentation?
- [x] Has the project adopted Django Commons's Code of Conduct?

### Who will be the new maintainers of the project?

@matthiask
@tim-schilling

**Comment by matthiask** [comment]
I'm worried about the lack of progress here. 

https://github.com/jazzband/help/issues?q=+is%3Aissue+label%3Atransfer-out+  -- no transfers actually happened, either people are waiting or they are content to stay with Jazzband. I really don't want to think about [the backup plan](https://github.com/jazzband/django-debug-toolbar/issues/1918#issuecomment-2132252812). OTOH, what else can we do than complain and put pressure on Jannis?

**Comment by carltongibson** [comment]
@matthiask I'd wager Jannis is just occupied. I would nudge him directly, and say _Please_ give it the moment it needs. (🤹 right 🙂)

**Comment by tim-schilling** [comment]
Makes sense. I can send something over. Thank you both for the thoughts.

**Comment by tim-schilling** [comment]
I'm going to look at getting PyPI prepped, a PR to use the new release process for the toolbar and a PR here for adding the repo.

**Comment by matthiask** [comment]
@tim-schilling Did you get an answer from Jannis regarding the move? If not I'll happily send a kind reminder.

**Comment by tim-schilling** [comment]
I have not. The step we need is for the repo to be transferred to me and then I'll transfer it to Django Commons. I suspect you should be able to receive and forward the repo as well if that's easier in some way.

**Comment by cunla** [comment]
@tim-schilling this is done, right?

**Comment by matthiask** [comment]
@cunla yep!
