### ISSUE TITLE
🛬 [INBOUND] - django-tasks-scheduler

### ISSUE THREAD

**Issue by cunla** [django-commons/membership#35]
### What's the URL to the project?

https://github.com/dsoftwareinc/django-tasks-scheduler

### Who are the current maintainers?

cunla

### Does the project have the required attributes?

- [X] Does the project have tests?
- [X] Does the project have documentation?
- [X] Has the project adopted Django Commons's Code of Conduct?

### Who will be the new maintainers of the project?

cunla

**Comment by tim-schilling** [comment]
Approved? I guess we don't have a process for this.
