### ISSUE TITLE
✋ [MEMBER] - Mogost

### ISSUE THREAD

**Issue by Mogost** [django-commons/membership#36]
### Why do you want to join?

I contribute to some open-source projects around and about Django. 
In addition to this, my [JazzBand issue appears](https://github.com/jazzband/help/issues/196) in the @django-commons description.
I like the idea of @django-commons. 

### Which project(s) are you looking to contribute to?

There aren't many projects here yet, but I think when there are more I'll be able to contribute.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Welcome aboard! Thank you for your work in the community too!

**Comment by Mogost** [comment]
@tim-schilling done!
