### ISSUE TITLE
✋ [MEMBER] - browniebroke

### ISSUE THREAD

**Issue by browniebroke** [django-commons/membership#37]
### Why do you want to join?

I'm one of the maintainers of cookiecutter-django and I often contribute to the projects that the template depend on. I'm also working with Django at my day job and contribute to various Django packages as a result. 

### Which project(s) are you looking to contribute to?

Dependencies of my own projects mainly, if/when they get transferred to this organisation. 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thank you, welcome aboard!
