### ISSUE TITLE
✋ [MEMBER] - ddabble

### ISSUE THREAD

**Issue by ddabble** [django-commons/membership#40]
### Why do you want to join?

Hey there! Being a current member of Jazzband, and a big fan of the maintainer-/contributor-focused goals of Django Commons, I'd like to join to be able to help and contribute to projects in the same way 🙂

### Which project(s) are you looking to contribute to?

Mostly dependencies of other projects I'm working on (if they were to be transferred to Django Commons), but also any other project that needs help and that I'd feel qualified to help with. The former would include [`django-simple-history`](https://github.com/jazzband/django-simple-history), which I think could benefit from being transferred over!

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Hi @ddabble, I created a PR to add you and you should get an invite once it is merged.

Regarding [django-simple-history](https://github.com/jazzband/django-simple-history), are you the main maintainer at the moment? if so, please open an [Transfer In](https://github.com/django-commons/membership/issues/new?assignees=django-commons%2Fadmins&labels=Transfer+project+in&projects=&template=transfer-project-in.yml&title=%F0%9F%9B%AC+%5BINBOUND%5D+-+%3Cproject%3E) issue, and we will schedule a short session to transfer it.

**Comment by tim-schilling** [comment]
Hi @ddabble! Great to see you here. 

It may be a good idea to open an issue on the history repo first to get Trey's buy-in, then start the rest of the process.

I've long thought simple history would be a good candidate to move, but was waiting to have more free time to start that conversation.

**Comment by ddabble** [comment]
@cunla @tim-schilling Great, thanks for the warm welcome! 😊

Together with Tim, we're the only active maintainers of django-simple-history, but none of us have admin permissions... From the "Leads" section of https://jazzband.co/projects/django-simple-history, @treyhunner @rossmechanic are the only ones with admin permissions (apart from @jezdez), though I'm not sure about the extent of their privileges, due to https://github.com/jazzband/django-simple-history/pull/1305#issuecomment-1987427992 🤔

In any case, I agree with Tim that the first step would be to open an issue to get Trey (and Ross, if he's still active) on board 🙂 I'm not sure I have the capacity to start that conversation this weekend, but perhaps within a few weeks - unless one of you get to it first :)

**Comment by treyhunner** [comment]
I'm on board with transferring django-simple-history to django-commons, but I believe we would need @jezdez to do the transfer.
