### ISSUE TITLE
🏗️ [ADMIN] - mkalioby

### ISSUE THREAD

**Issue by mkalioby** [django-commons/membership#47]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I like to help the community to help open-source maintainers

### Please tell us about your packaging experience?

I'm the main contributor and admin for django-mfa2 and django-passkeys which are both stared less than 500 times and downloaded round ~250k times.

### Please tell us about your GitHub Actions experience?

In open of the companies, I was consulting fo, everything was in GitHub actions including PR validation and then the release. This led me to integrate this in django-passkeys to have fully automated testing using toxic and coverage.

### How long do you expect to be involved with Django Commons?

May be a year or 2 years. As I always try to help the community.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thank you for reaching out @mkalioby! I wanted to respond that we see your issue and we're communicating behind the scenes currently on how to proceed. If you're curious about the role, you can see an earlier discussion here: https://github.com/orgs/django-commons/discussions/19

**Comment by mkalioby** [comment]
Thanks Tim, will try to catch up 🤠

**Comment by tim-schilling** [comment]
Hi @mkalioby, for now we're not accepting new admins. We plan on revisiting the admin team membership in a few months when things are less new. We will reach out to all folks who have volunteered to be an admin then. Thank you for offering to help! We'd love to have you engaged in our little community here regardless of your official role!

**Comment by tim-schilling** [comment]
@mkalioby I messed up earlier and forgot to add you to the community. Sorry about that! I've fixed that issue now. You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.

**Comment by mkalioby** [comment]
Hello Tim,

It is accepted. Thanks

**Comment by cunla** [comment]
@mkalioby, do you mind setting your [organization membership as public](https://github.com/orgs/django-commons/people)?

**Comment by mkalioby** [comment]
Done
