### ISSUE TITLE
✋ [MEMBER] - bckohan

### ISSUE THREAD

**Issue by bckohan** [django-commons/membership#49]
### Why do you want to join?

I'm heavily leveraged personally and at work on the health of the Django package ecosystem and would like to do my part to keep it going strong!

### Which project(s) are you looking to contribute to?

I would eventually like to transfer my Django packages to commons and maintain them here. I'm more interested in adding new features to packages I use (none currently in commons) but also recognize an obligation to help keep other packages updated.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Welcome aboard @bckohan! Thank you for joining!

Please feel free to start or contribute to a discussion
