### ISSUE TITLE
New Member!

### ISSUE THREAD

**Issue by nanorepublica** [django-commons/membership#5]
### Why do you want to join?

Hey Tim, this org looks interesting to me and always happy to help where I can :) 

I also might transfer a couple of my projects in to here!

### Which project(s) are you looking to contribute to?

I might bring my own, but otherwise, any that I have experience with. 

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Approved

**Comment by tim-schilling** [comment]
Nice, it actually worked!

**Comment by tim-schilling** [comment]
Hi @nanorepublica, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people

**Comment by nanorepublica** [comment]
Done!
