### ISSUE TITLE
✋ [MEMBER] - jacklinke

### ISSUE THREAD

**Issue by jacklinke** [django-commons/membership#51]
### Why do you want to join?

I believe in the goals of django-commons, and was excited to hear about it at the open spaces discussion at DjangoCon. I think I could help here and there with upkeep and maintenance on packages.

### Which project(s) are you looking to contribute to?

Of the two currently existing packages, django-fsm-2 seems particularly interesting.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Welcome @jacklinke

**Comment by tim-schilling** [comment]
Hi @jacklinke, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people

**Comment by jacklinke** [comment]
Done! I actually had no idea that was a thing. Looking at the other orgs I belong to now lol
