### ISSUE TITLE
✋ [MEMBER] - <salty-ivy>

### ISSUE THREAD

**Issue by salty-ivy** [django-commons/membership#53]
### Why do you want to join?

I have been contributing  in django-debug-toobar which would soon be part of this community, I would like to continue my participation in the library and many other projects within this community. 

contributor at **django**.
member at **wagtail**.

### Which project(s) are you looking to contribute to?

Incoming, django-debug-toolbar.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Welcome @salty-ivy

**Comment by salty-ivy** [comment]
> Welcome @salty-ivy

Thanks a lot @cunla

**Comment by Stormheg** [comment]
Amazing, thanks for your work on the debug toolbar @salty-ivy 🫶
