### ISSUE TITLE
🛬 [INBOUND] - django-typer

### ISSUE THREAD

**Issue by bckohan** [django-commons/membership#58]
### What's the URL to the project?

https://github.com/bckohan/django-typer

### Who are the current maintainers?

Brian Kohan

### Does the project have the required attributes?

- [X] Does the project have tests?
- [X] Does the project have documentation?
- [X] Has the project adopted [Django Commons's Code of Conduct](https://github.com/django-commons/membership/blob/main/CODE_OF_CONDUCT.md)?

### Who will be the new maintainers of the project?

I (Brian Kohan) will continue to maintain the project. I'm hopeful I might find additional maintainers through commons or that @oliverandrich might be interested!

**Comment by oliverandrich** [comment]
Following the invitation above, I am willing to be a co-maintainer along with @bckohan.

**Comment by bckohan** [comment]
Glad to have you onboard @oliverandrich!!

I think for them to onboard you as a repo admin, you need to [join as a member](https://github.com/django-commons/membership?tab=readme-ov-file#how-to-join-as-a-contributor).

**Comment by cunla** [comment]
Hi Brian & Oliver,

Let's have a short meeting to transfer the project: https://cal.com/daniel-moran/dc-meeting

**Comment by bckohan** [comment]
@cunla @oliverandrich  is not a current maintainer, but we'd like to add him after the transfer. Not sure if he needs to be at this meeting. He's also in Germany and I'm in California so it might be hard for us to find a time that works for both of us.

I went ahead and grabbed a time slot at 11:45am PDT tomorrow.
