### ISSUE TITLE
✋ [MEMBER] - oliverandrich

### ISSUE THREAD

**Issue by oliverandrich** [django-commons/membership#59]
### Why do you want to join?

I would love to join django-commons as I see a lot of benefit for the community, if more and more projects are maintained under a common umbrella. I see especially benefits for single person projects like my own django-tailwind-cli project or a project like django-typer. The reason I am eager to join right now, is that I agreed to help to maintain django-typer which is a pending transferal request. But I also consider to move django-tailwind-cli to django-commons.

### Which project(s) are you looking to contribute to?

django-typer currently. But I plan to move django-tailwind-cli to django-commons too if it is considered a valuable contribution.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Thank you @oliverandrich for joining! You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.

**Comment by oliverandrich** [comment]
@cunla Thank you for accepting my application and allowing me to be part of django-commons. I have set my membership to public.

**Comment by tim-schilling** [comment]
Thank you @oliverandrich, welcome aboard!

**Comment by Stormheg** [comment]
Welcome @oliverandrich 🧡
