### ISSUE TITLE
✋ [MEMBER] - unmonoqueteclea

### ISSUE THREAD

**Issue by unmonoqueteclea** [django-commons/membership#63]
### Why do you want to join?

This is a great project, and I would love to be part of it. After several years of using Django across different companies, I believe it's now my turn to give back to the community.

### Which project(s) are you looking to contribute to?

I still need to decide it, I will wait a bit until there are many different projects available

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by Stormheg** [comment]
Welcome aboard! You should have received an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.
