### ISSUE TITLE
🏗️ [ADMIN] - @RealOrangeOne

### ISSUE THREAD

**Issue by RealOrangeOne** [django-commons/membership#68]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

Much like Jazzband, I'm looking forward to seeing what the Django community do with the "commons" org, and wantto see it succeed.

Particularly, I'm interested in contributing my experience in security and performance, having been on Wagtail's security team for over 18 months, and generally working with Django for almost a decade.

### Please tell us about your packaging experience?

I maintain [a number](https://github.com/RealOrangeOne?tab=repositories&q=django&type=&language=&sort=) of Django packages personally, and I've been on the Wagtail core team for around 6 months.

### Please tell us about your GitHub Actions experience?

GitHub Actions is my go-to for CI/CD at the moment - I'm very comfortable with it. Terraform is equally comfortable to me.

### How long do you expect to be involved with Django Commons?

I'm expecting to be _involved_ for the long haul. My availability may come and go, but I won't be disappearing.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Hi @RealOrangeOne, for now we're not accepting new admins. We plan on revisiting the admin team membership in a few months when things are less new. We will reach out to all folks who have volunteered to be an admin then. Thank you for offering to help! We'd love to have you engaged in our little community here regardless of your official role! We do our best to have our discussions in public where folks can engage and stay up to date.

I'm going to get you added as a member though!

**Comment by tim-schilling** [comment]
Done! You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.

**Comment by Stormheg** [comment]
@RealOrangeOne Welcome Jake! Great to see you here 👋

**Comment by cunla** [comment]
@RealOrangeOne, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)?

**Comment by RealOrangeOne** [comment]
I could have sworn it was... But yes, now updated
