### ISSUE TITLE
🏗️ [ADMIN] - knyghty

### ISSUE THREAD

**Issue by knyghty** [django-commons/membership#7]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

This idea has floated around in my head for a good amount of time now and I'm glad someone has taken the initiative to do it. I want to help it be successful and hopefully avoid some of the problems with Jazzband.

### Please tell us about your packaging experience?

Not a lot, I have a few barely used packages listed below, and maintain a template that I've just started using at https://github.com/knyghty/cookiecutter-django-package

- https://github.com/knyghty/django-admin-demo - not strictly a package but a repo used by people testing admin changes
- https://github.com/knyghty/django-rq-email-backend - stolen from Jeff and modernised
- https://github.com/knyghty/django-snakeoil - SEO stuff
- Secret project (to hopefully be revealed at DCEU)

### Please tell us about your GitHub Actions experience?

Yeah I frikkin love that stuff dude. Never looked back after running away from Travis, Jenkins, Circle, etc.

Wouldn't say I know everything there is to know, but I have the basics down. You can see how I usually put this stuff together e.g. https://github.com/knyghty/django-rq-email-backend/blob/main/.github/workflows/ci.yml

### How long do you expect to be involved with Django Commons?

I suppose... indefinitely enough. At least a year I'd say. I'd probably not even be super active in the next month or so as I've a lot of stuff on at the moment. But I can make time soonish.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks Tom! I'm going to let this sit for a week to give time to other folks to apply.

**Comment by tim-schilling** [comment]
Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Hi Tom, would you be willing to get on the Code of Conduct team for the org? It would be managed via a Google Group, where upon a report occurring, we'd collect the details of the incident, discuss how to handle things, then come to an agreement on a path forward.

At the conclusion of each report, we would send an email to the admin team and the CoC team with our decision (provides accountability and transparency). As you can likely imagine, the involvement will be low until there's an incident.

Please let me know if this is something you'd be interested and available to do? We're looking at a 9-12 month cycle before we reassess team structures. Though you're free to step down at any point.

**Comment by knyghty** [comment]
Sounds good to me. I'm a bit sad about using Google Groups but also not sure of a better alternative.

**Comment by tim-schilling** [comment]
Thank you! Agreed on the google groups count. It's what we all knew of and the point of this is to get something in place rather than reinvent wheels. :shrug: I'm definitely open to changing it.

The next steps will be posted to that google group in the next month or so pending people's availability.
