### ISSUE TITLE
✋ [MEMBER] - elineda

### ISSUE THREAD

**Issue by elineda** [django-commons/membership#74]
### Why do you want to join?

Hello, 
I'm elineda, I contribute to django debug toolbar.
As the toolbar will migrate on django common, I would like to have the membership for have elevated permission on this project.
And this is the 4th sentence :)

### Which project(s) are you looking to contribute to?

Django debugtoolbar

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by Stormheg** [comment]
Welcome @elineda 🙌 – you should have received an invitation to join.

[I see @tim-schilling already added you to the committer team of the debug toolbar](https://github.com/django-commons/membership/blob/9e73859d519f6b7483d194cc5f66ec95eadf4357/terraform/production/repositories.tfvars#L80), pending it moving over to Commons 👍 

If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)? This helps Django Commons grow.
