### ISSUE TITLE
✋ Velda Kiara- <VeldaKiara>

### ISSUE THREAD

**Issue by VeldaKiara** [django-commons/membership#76]
### Why do you want to join?

I want to join to continue contributing to Django Debug Toolbar. As well as contribute to other third party Django packages.

### Which project(s) are you looking to contribute to?

Django Debug Toolbar

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by cunla** [comment]
Thank you @VeldaKiara for joining! You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)?

This helps Django Commons grow.

**Comment by VeldaKiara** [comment]
Yes. I wil.

**Comment by Stormheg** [comment]
Welcome!
