### ISSUE TITLE
🏗️ [ADMIN] - @joshuadavidthomas

### ISSUE THREAD

**Issue by joshuadavidthomas** [django-commons/membership#8]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

As I've gotten more experience, I've realized the value in sharing what I've learned along the way. I try to blog, but I'm not much of a writer and writing well takes a ton of time. Additionally, I try to contribute where I can to public third-party packages. 

If I could step into an admin role where I can help out maintainers with some of the drudgery, meta stuff around maintaining a package, so they can focus more of their attention on the package itself, well I think I would be a good fit for that. In my capacity as a member of the Jazzband org, that's generally the type of contributions I have made. 

Plus, through this organization, in addition to the typical installable Django apps, I could see where a catalog of public GitHub Actions or Python/Django packages around maintaining packages that is used by Django Commons repos but that *anyone* could use would be a great contribution to the community.

### Please tell us about your packaging experience?

Through my work, I maintain a number of third-party Django packages:

- [`django-email-relay`](https://github.com/westerveltco/django-email-relay)
- [`django-flyio`](https://github.com/westerveltco/django-flyio)
- [`django-opfield`](https://github.com/westerveltco/django-opfield)
- [`django-q-registry`](https://github.com/westerveltco/django-q-registry)
- [`django-simple-nav`](https://github.com/westerveltco/django-simple-nav)
- [`django-twc-toolbox`](https://github.com/westerveltco/django-twc-toolbox)
- [`wagtail-heroicons`](https://github.com/westerveltco/wagtail-heroicons)

As well as two templates, one for actual Django projects and one for installable packages/apps:

- [`django-twc-package`](https://github.com/westerveltco/django-twc-package)
- [`django-twc-project`](https://github.com/westerveltco/django-twc-project)

None of them are super popular, some I maintain better than others (😂), but they all share the same modern Python packaging approach using only a `pyproject.toml` file and `hatch` as a build backend.

I also have experience building and packaging Python projects using other approaches (`setup.{cfg,py}`, `setuptools`, `build`, etc..) but it has been a bit since meaningfully interacting with packages in that way. Similarly, I have used tools like `poetry` in the past and have dabbled with `rye` on a couple projects.

### Please tell us about your GitHub Actions experience?

I have extensive GitHub Actions experience. As mentioned previously, as a Jazzband member that's generally the types of contributions I have made: tweaking the job matrix when a new Python/Django version is released or and old one goes EOL.

I'm also big into fully leveraging the platform to help making maintaining a project easier. For instance, instead of maintaining a job matrix by hand, I use the ability for `nox` (my testing tool of choice for distributable packages) to output it's own job matrix in a JSON format and use that to create the test matrix for GitHub Actions: 

https://github.com/westerveltco/django-simple-nav/blob/39b54464892910c4c1f140a103776526dd15efac/.github/workflows/test.yml#L32-L34
https://github.com/westerveltco/django-simple-nav/blob/39b54464892910c4c1f140a103776526dd15efac/.github/workflows/test.yml#L42

As well, going beyond the typical `push` or `pull_request` workflow triggers, I have fully automated the release process here using the `release.released` trigger and the PyPI Trusted Publisher authentication: https://github.com/westerveltco/django-simple-nav/blob/39b54464892910c4c1f140a103776526dd15efac/.github/workflows/release.yml

I have also written a few custom actions to be used in other GHA workflows, though nothing anything more involved than the composite actions.

### How long do you expect to be involved with Django Commons?

As long as the time requirements were reasonable, I see no reason not to be involved in at least some capacity as long as I'm still using Django. If the time burden became too much for me to handle or I transitioned to a new position where I was not using Django day-to-day, I would reassess then.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks Josh! I'm going to let this sit for a week to give time to other folks to apply.

**Comment by tim-schilling** [comment]
Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Thanks for your interest Josh! Right now the roster is full, but the expectation is that we'll cycle people in and out of roles over time. I'll circle back with you when we get to that point.

**Comment by joshuadavidthomas** [comment]
@tim-schilling Thanjs for the update. That's very exciting that there was so much interest this early in helping out! 🎉

Happy to help out the mission of the org in anyway I can. 😄

**Comment by tim-schilling** [comment]
Hi @joshuadavidthomas, do you mind marking your membership as public? This helps show people have confidence in the org. https://github.com/orgs/django-commons/people
