### ISSUE TITLE
✋ [MEMBER] - @ulgens

### ISSUE THREAD

**Issue by ulgens** [django-commons/membership#84]
### Why do you want to join?

I like the idea and I want to be a part of it. I was already helping to maintain several packages in the Django ecosystem by doing small chores and I'd like take a bit more serious responsibility in a well defined organization.want to be a part of it. I was already helping to maintain several packages in the Django ecosystem by doing small chores, and I'd like to take a bit more serious responsibility in a well-defined

### Which project(s) are you looking to contribute to?

Nothing in particular now, but I have several packages in mind that are not yet in the group but I believe they are perfect candidates (e.g django-rest-framework, django-extensions...)

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by ryancheley** [comment]
Thank you @ulgens for joining. You'll get an invite email from GitHub. You'll have one week to accept that. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)?

This helps Django Commons grow.

**Comment by ulgens** [comment]
Got the email and accepted it. Set my membership visibility to public.

Thanks a lot 🌷

**Comment by Stormheg** [comment]
Welcome Ülgen!

**Comment by tim-schilling** [comment]
Welcome Ülgen! It's great to see you here too. I've seen your name in a bunch of areas over the last few years.

**Comment by ulgens** [comment]
@tim-schilling Thank you for the warm welcome; it's nice to be here. I hope they are good memories 🌷
