### ISSUE TITLE
✋ [MEMBER] - <amirreza8002>

### ISSUE THREAD

**Issue by amirreza8002** [django-commons/membership#88]
### Why do you want to join?

i like to contribute to open source
i have a few django related projects that could benefit from community support

### Which project(s) are you looking to contribute to?

i have a few projects of my own, but in general i'm open to anything within my ability

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by Stormheg** [comment]
Welcome @amirreza8002 👋 👋

**Comment by amirreza8002** [comment]
hi🙌
thank you 🙏

**Comment by tim-schilling** [comment]
Great to see you here @amirreza8002! I've seen your handle on the discord quite a bit too

**Comment by amirreza8002** [comment]
hi👋
thank you 
yeah the discord crowd are great 
been learning a lot from them

**Comment by Stormheg** [comment]
@amirreza8002 I forgot to ask, could you please set your [organization membership to public](https://github.com/orgs/django-commons/people)?

This helps Django Commons grow.

**Comment by amirreza8002** [comment]
hi
I'm on the road and GitHub mobile is not very friendly.
god willing I'll get to it in a day or two

**Comment by Stormheg** [comment]
Sure no problem, drive safely!
