### ISSUE TITLE
🏗️ [ADMIN] - matthiask

### ISSUE THREAD

**Issue by matthiask** [django-commons/membership#9]
### DSF member

- [X] I am a DSF member

### Why do you want to join?

I want to help out and I also think I want to propose a move of some of my own projects here since I think that django-commons would be a better place than my personal profile. I'm going to follow the official procedure for this of course and not just move projects into the organization because I can.

### Please tell us about your packaging experience?

TBH I don't yet have experience using e.g. trusted publishing using PyPI. That's something I'm going to learn soon-ish. I certainly have a lot of experience when it comes to releasing Python packages generally.

### Please tell us about your GitHub Actions experience?

I have been using GitHub actions for a long time; I haven't authored my own reusable action, but done about everything else.

### How long do you expect to be involved with Django Commons?

I except to work with and on Django for years to come, and I expect to stay an active member of Django Commons for the same time, except if things change (as they did with Jazzband). I'm also happy if I can step back, and let others do the work and take the blame/praise for it so maybe the involvement won't be as long.

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by tim-schilling** [comment]
Thanks Matthias! I'm going to let this sit for a week to give time to other folks to apply.

**Comment by tim-schilling** [comment]
Please see https://github.com/orgs/django-commons/discussions/19. I'm not sure if the tag actually pinged you.

**Comment by tim-schilling** [comment]
Hi Matthias, would you be willing to get on the Code of Conduct team for the org? It would be managed via a Google Group, where upon a report occurring, we'd collect the details of the incident, discuss how to handle things, then come to an agreement on a path forward.

At the conclusion of each report, we would send an email to the admin team and the CoC team with our decision (provides accountability and transparency). As you can likely imagine, the involvement will be low until there's an incident.

Please let me know if this is something you'd be interested and available to do? We're looking at a 9-12 month cycle before we reassess team structures. Though you're free to step down at any point.

**Comment by matthiask** [comment]
Yes, I'm interested in that! Thank you. (I think I've already been invited to the google group?)

**Comment by tim-schilling** [comment]
Great, thank you! And yes, we had a slight mistiming on our end. The next steps will be posted to that google group in the next month or so pending people's availability.
