### ISSUE TITLE
✋ [MEMBER] - <pauloxnet>

### ISSUE THREAD

**Issue by pauloxnet** [django-commons/membership#90]
### Why do you want to join?

Contributing to important Django projects, sharing the responsabilities with the community, and assuring a future for some important Django packages.

### Which project(s) are you looking to contribute to?

Continue to contribute to the same palrojects I used to contribute in Jazzband (eg: django-debug-toolbar, ...), 

Try to move here the project in Jazzband that are stale due to missing maintainer actions (eg: django-configurations, ...)

It would be also useful try to have here, all the Django dependencies that we use in the Django website, especially packages anymore updated (eg: django-pubsub,...)

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by Stormheg** [comment]
Great to have you here Paolo! 🚀

**Comment by tim-schilling** [comment]
That's quite the plan for us, I like it! Let us know how we can support you with those moves.

**Comment by Stormheg** [comment]
@pauloxnet I forgot to ask, could you please set your [organization membership to public](https://github.com/orgs/django-commons/people)?

This helps Django Commons grow.

**Comment by pauloxnet** [comment]
> @pauloxnet I forgot to ask, could you please set your [organization membership to public](https://github.com/orgs/django-commons/people)?
> 
> This helps Django Commons grow.

Sure, every time I forgot about that. Done.
