### ISSUE TITLE
✋ [MEMBER] - @sobolevn

### ISSUE THREAD

**Issue by sobolevn** [django-commons/membership#95]
### Why do you want to join?

Hi 👋 
I am a long time Django user, Django contributor, TypedDjango maintainer, Django Software Foundation Member (and many other things I do in opensource).

I mainly look to see how this project works and then maybe transfer my own projects here :)

### Code of Conduct

- [X] I agree to follow Django Commons's Code of Conduct

**Comment by Stormheg** [comment]
Welcome @sobolevn 👋 

You should have received an invitation to join. If you don't mind, after accepting, can you set your [organization membership as public](https://github.com/orgs/django-commons/people)?

This helps Django Commons grow.

**Comment by sobolevn** [comment]
Done! Thanks a lot for your efforts! I really hope that this project will help to improve Django world!

<img width="309" alt="Снимок экрана 2024-11-01 в 17 03 18" src="https://github.com/user-attachments/assets/8c71b233-7a80-47bd-8a4d-c67b1ac5ed65">
